## Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
## SPDX-License-Identifier: Apache-2.0

name: Sample App Deployment - Dotnet S3
on:
  workflow_dispatch: # be able to run the workflow on demand
  push:
permissions:
  id-token: write
  contents: read

jobs:
  upload-sample-app-zip:
    strategy:
      fail-fast: false
      matrix:
        aws-region: [ 'us-east-1']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.E2E_IAD_TEST_ACCOUNT_ARN }}
          aws-region: us-east-1

      # - name: Retrieve account
      #   uses: aws-actions/aws-secretsmanager-get-secrets@v1
      #   with:
      #     secret-ids:
      #       ACCOUNT_ID, region-account/${{ matrix.aws-region }}

      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     role-to-assume: arn:aws:iam::${{ env.ACCOUNT_ID }}:role/${{ secrets.E2E_TEST_ROLE_ARN }}
      #     aws-region: ${{ matrix.aws-region }}

      - name: Build Sample App Zip
        working-directory: sample-apps/dotnet
        run: zip -r dotnet-sample-app.zip .

      - name: Upload to S3
        working-directory: sample-apps/dotnet
        run: aws s3api put-object --bucket aws-appsignals-sample-app-prod-jeel --body ./dotnet-sample-app.zip --key dotnet-sample-app.zip

      - name: Upload Windows Script to S3
        working-directory: sample-apps/dotnet
        run: |
          aws s3api put-object --bucket aws-appsignals-sample-app-prod-jeel --body ./dotnet-ec2-win-main-setup.ps1 --key dotnet-ec2-win-main-setup.ps1
          aws s3api put-object --bucket aws-appsignals-sample-app-prod-jeel --body ./dotnet-ec2-win-remote-setup.ps1 --key dotnet-ec2-win-remote-setup.ps1
          aws s3api put-object --bucket aws-appsignals-sample-app-prod-jeel --body ./amazon-cloudwatch-agent.json --key amazon-cloudwatch-agent.json
          

