## Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
## SPDX-License-Identifier: Apache-2.0

name: Sample App Deployment - Dotnet ECR
on:
  workflow_dispatch: # be able to run the workflow on demand
  push:
permissions:
  id-token: write
  contents: read

jobs:
  upload-main-service-image:
    strategy:
      fail-fast: false
      matrix:
        aws-region: [ 'us-east-1' ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.E2E_IAD_TEST_ACCOUNT_ARN }}
          aws-region: us-east-1

      # - name: Retrieve account
      #   uses: aws-actions/aws-secretsmanager-get-secrets@v1
      #   with:
      #     secret-ids:
      #       ACCOUNT_ID, region-account/${{ matrix.aws-region }}

      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     role-to-assume: arn:aws:iam::${{ env.ACCOUNT_ID }}:role/${{ secrets.E2E_TEST_ROLE_ARN }}
      #     aws-region: ${{ matrix.aws-region }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Docker compose build
        working-directory: sample-apps/dotnet
        run: |
          docker compose build

      - name: Upload Main Service Image
        run: |
          docker tag dotnetsampleapp/frontend-service 890742580622.dkr.ecr.us-east-1.amazonaws.com/dotnet-sample-app:6.0
          docker push 890742580622.dkr.ecr.us-east-1.amazonaws.com/dotnet-sample-app:6.0
      # - name: Upload Remote Service Image
      #   run: |
      #     docker tag dotnetsampleapp/remote-service ${{ env.ACCOUNT_ID }}.dkr.ecr.${{ matrix.aws-region }}.amazonaws.com/${{ secrets.APP_SIGNALS_DOTNET_E2E_RE_SA_IMG }}
      #     docker push ${{ env.ACCOUNT_ID }}.dkr.ecr.${{ matrix.aws-region }}.amazonaws.com/${{ secrets.APP_SIGNALS_DOTNET_E2E_RE_SA_IMG }}
